'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Connect.Modules.UserManagement.AccountManagement

    Partial Public Class Reports

        '''<summary>
        '''rptReports control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptReports As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''cmdNewReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdNewReport As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdBack control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdBack As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''pnlReportForm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlReportForm As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''plReportName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plReportName As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtReportName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtReportName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plReportSql control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plReportSql As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtReportSql control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtReportSql As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdAddReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdAddReport As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdUpdateReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdateReport As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdDeleteReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdDeleteReport As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdCancelReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCancelReport As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
