'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Connect.Modules.UserManagement.AccountManagement

    Partial Public Class Templates

        '''<summary>
        '''plTheme control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTheme As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''drpThemes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpThemes As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''cmdCopySelected control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCopySelected As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdDeleteSelected control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdDeleteSelected As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''pnlLocales control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlLocales As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plLocale control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLocale As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''drpLocales control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpLocales As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plUseTheme control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plUseTheme As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkUseTheme control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkUseTheme As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''pnlTemplateName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlTemplateName As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plTemplateName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTemplateName As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtTemplateName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTemplateName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''AccountUpdateTemplatesTabs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AccountUpdateTemplatesTabs As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblCreateFormTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCreateFormTemplate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblAccountFormTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAccountFormTemplate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblProfileFormTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProfileFormTemplate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEmailAddedToRole control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmailAddedToRole As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEmailRemovedFromRole control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmailRemovedFromRole As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblRoleStatusChanged control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRoleStatusChanged As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEmailPasswordReset control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmailPasswordReset As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEmailAccountData control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmailAccountData As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEmailAccountCreated control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmailAccountCreated As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtCreateFormTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCreateFormTemplate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtAccountFormTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAccountFormTemplate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtProfileFormTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtProfileFormTemplate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtEmailAddedToRole control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmailAddedToRole As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtEmailRemovedFromRole control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmailRemovedFromRole As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtEmailRoleStatusChanged control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmailRoleStatusChanged As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtEmailPasswordReset control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmailPasswordReset As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtEmailAccountData control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmailAccountData As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtEmailAccountCreated control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmailAccountCreated As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdUpdateExit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdateExit As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
