'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Connect.Modules.UserManagement.AccountManagement

    Partial Public Class View

        '''<summary>
        '''pnlError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlError As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblError As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''pnlSuccess control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlSuccess As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblSucess control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSucess As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''pnlCreateAccount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlCreateAccount As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''cmdCreateAccount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCreateAccount As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''pnlBackToList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlBackToList As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''cmdBack control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdBack As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''pnlSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlSearch As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''txtSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSearch As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''ctlRoles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlRoles As Global.DotNetNuke.Web.UI.WebControls.DnnTreeView

        '''<summary>
        '''pnlHardDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlHardDelete As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''btnHardDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnHardDelete As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''pnlExport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlExport As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''btnExport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnExport As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''pnlReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlReport As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''drpReports control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpReports As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''btnReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnReport As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''pnlGrid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlGrid As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''UserGridTabs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UserGridTabs As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblGridTab control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblGridTab As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPreferencesTab control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPreferencesTab As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''grdUsers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdUsers As Global.DotNetNuke.Web.UI.WebControls.DnnGrid

        '''<summary>
        '''cmdBulkDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdBulkDelete As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdBulkRemove control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdBulkRemove As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lblSearchOptions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSearchOptions As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''chkSearchCols control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSearchCols As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''lblGridSetup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblGridSetup As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''chkGridOptions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkGridOptions As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''lblPageSize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPageSize As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''drpPageSize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpPageSize As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''btnApplyOptions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnApplyOptions As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''pnlUser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlUser As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''UserDetailTabs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UserDetailTabs As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''tabAccount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tabAccount As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblAccountTab control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAccountTab As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''tabPassword control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tabPassword As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblPasswordTab control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPasswordTab As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''tabProfile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tabProfile As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblProfileTab control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProfileTab As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''tabRoles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tabRoles As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblRolesTab control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRolesTab As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''tabEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tabEmail As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblEmailTab control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmailTab As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''tabMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tabMessage As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblMessageTab control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMessageTab As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''tabSites control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tabSites As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblSitesTab control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSitesTab As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plhAdditionalTabs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plhAdditionalTabs As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''pnlAccountTab control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlAccountTab As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblAccountNote control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAccountNote As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''plhUser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plhUser As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''lblMemberSinceLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMemberSinceLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblMemberSince control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMemberSince As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblLastLoginLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLastLoginLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblLastLogin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLastLogin As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblLastActivityLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLastActivityLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblLastActivity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLastActivity As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblLastPasswordChangeLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLastPasswordChangeLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblLastPasswordChange control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLastPasswordChange As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblLastLockoutLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLastLockoutLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblLastLockout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLastLockout As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblUserOnlineStatusLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblUserOnlineStatusLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblUserOnlineStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblUserOnlineStatus As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblAuthorizedStatusLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAuthorizedStatusLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblAuthorizedStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAuthorizedStatus As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblLockoutStatusLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLockoutStatusLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblLockoutStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLockoutStatus As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblForcePasswordChangeLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblForcePasswordChangeLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblForcePasswordChange control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblForcePasswordChange As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''cmdUpdateAccount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdateAccount As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdUnlockAccount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUnlockAccount As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdAuthorizeAccount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdAuthorizeAccount As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdForcePasswordChange control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdForcePasswordChange As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdDeleteAccount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdDeleteAccount As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdRestoreAccount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdRestoreAccount As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''pnlPasswordTab control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlPasswordTab As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblPasswordNote control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPasswordNote As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''pnlResetButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlResetButton As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''cmdResetPasswordLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdResetPasswordLink As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''pnlPassword_Step1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlPassword_Step1 As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblPassword1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPassword1 As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtPassword1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPassword1 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblPassword2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPassword2 As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtPassword2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPassword2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdUpdatePassword control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdatePassword As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''pnlPassword_Step2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlPassword_Step2 As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''txtNotifyPasswordSubject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNotifyPasswordSubject As Global.DotNetNuke.Web.UI.WebControls.DnnTextBox

        '''<summary>
        '''txtNotifyPasswordBody control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNotifyPasswordBody As Global.DotNetNuke.Web.UI.WebControls.DnnEditor

        '''<summary>
        '''btnNotifyPassword control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnNotifyPassword As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnNotifyPasswordSkip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnNotifyPasswordSkip As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''pnlProfileTab control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlProfileTab As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblProfileNote control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProfileNote As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''plhProfile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plhProfile As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''cmdUpdateProfile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdateProfile As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''pnlRolesTab control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlRolesTab As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblRolesNote control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRolesNote As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''pnlRoleChange_Step1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlRoleChange_Step1 As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''drpRoles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpRoles As Global.DotNetNuke.Web.UI.WebControls.DnnComboBox

        '''<summary>
        '''ctlRoleDatFrom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlRoleDatFrom As Global.DotNetNuke.Web.UI.WebControls.DnnDatePicker

        '''<summary>
        '''ctlRoleDateTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlRoleDateTo As Global.DotNetNuke.Web.UI.WebControls.DnnDatePicker

        '''<summary>
        '''btnAddToRole control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnAddToRole As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''grdUserRoles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdUserRoles As Global.DotNetNuke.Web.UI.WebControls.DnnGrid

        '''<summary>
        '''pnlRoleChange_Step2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlRoleChange_Step2 As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''txtNotifyRoleSubject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNotifyRoleSubject As Global.DotNetNuke.Web.UI.WebControls.DnnTextBox

        '''<summary>
        '''txtNotifyRoleBody control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNotifyRoleBody As Global.DotNetNuke.Web.UI.WebControls.DnnEditor

        '''<summary>
        '''btnNotifyRole control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnNotifyRole As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnNotifyRoleSkip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnNotifyRoleSkip As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''pnlEmailTab control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlEmailTab As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblEmailNote control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmailNote As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''txtNotifyUserSubject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNotifyUserSubject As Global.DotNetNuke.Web.UI.WebControls.DnnTextBox

        '''<summary>
        '''txtNotifyUserBody control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNotifyUserBody As Global.DotNetNuke.Web.UI.WebControls.DnnEditor

        '''<summary>
        '''btnNotifyUser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnNotifyUser As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''pnlMessageTab control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlMessageTab As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblMessageNote control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMessageNote As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblMessageSubject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMessageSubject As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtMessageSubject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMessageSubject As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblMessageBody control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMessageBody As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtMessageBody control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMessageBody As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnSendMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSendMessage As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''pnlSitesTab control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlSitesTab As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblSitesNote control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSitesNote As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''chkUserSites control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkUserSites As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''cmdUpdateSites control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdateSites As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''plhAdditonalControls control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plhAdditonalControls As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''pnlCreate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlCreate As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblCreateAccountNote control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCreateAccountNote As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''plhCreate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plhCreate As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''cmdAddAccount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdAddAccount As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdCancelCreate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCancelCreate As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
