'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Connect.Modules.UserManagement.AccountManagement

    Partial Public Class Settings

        '''<summary>
        '''lblAllowReports control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAllowReports As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkAllowReports control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAllowReports As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblAllowCreate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAllowCreate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkAllowCreate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAllowCreate As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblAllowDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAllowDelete As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkAllowDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAllowDelete As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblAllowHardDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAllowHardDelete As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkAllowHardDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAllowHardDelete As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblAllowExport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAllowExport As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkAllowExport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAllowExport As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblAllowedRoles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAllowedRoles As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkAllowedRoles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAllowedRoles As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''lblPreselectRole control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPreselectRole As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''drpPreselectRole control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpPreselectRole As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblUserTabs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblUserTabs As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkUserTabs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkUserTabs As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''lblAdditionalControls control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAdditionalControls As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtAditionalControls control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAditionalControls As Global.System.Web.UI.WebControls.TextBox
    End Class
End Namespace
